### ISSUE TITLE
Provide example for apps config

### ISSUE THREAD

**Issue by PVince81** [owncloud-ansible/owncloud#12]
The documentation should include an example that shows how the expected array should be structured.

As I'm not familiar yet with this syntax, it is difficult for me to infer from the code: https://github.com/owncloud-ansible/owncloud/blob/92f3f06f3a7f87d87b48a14efdd13f87d8528fe5/tasks/apps.yml#L15

**Comment by PVince81** [comment]
The documentation of "subelements()" isn't very clear to me as it has no examples so I tried several structures but did not manage to match whatever is expected here.

Here is my last attempt:
```yaml
owncloud_apps_config:
  parameters:
    core:      
    - attribute: "umgmt_set_password"
      value: "true"
    encryption:
    - attribute: "publicShareKeyId"
      value: "xxx"
    - attribute: "recoveryKeyId"
      value: "recoveryKey_1234567"
    - attribute: "yyy"
      value: "1"
```

@xoxys do you have a quick example for multiple values ?
