### ISSUE TITLE
Fix: Defining app config values breaks ansible script execution

### ISSUE THREAD

**Issue by d7oc** [owncloud-ansible/owncloud#69]
If the S3 configuration is given in the `owncloud_config_extra` section like this:

```
owncloud_config_extra:
  - objectstore:
      class: 'OCA\\Files_Primary_S3\\S3Storage'
      arguments:
        bucket: "owncloud"
        part_size: "5242880"
        concurrency: "5"
        options:
          version: "2006-03-01"
          region: "us-east-1"
          credentials:
            key: "username"
            secret: "password"
          use_path_style_endpoint: true
          endpoint: "http:\/\/hostname:8000"
```

Ansible aborts the execution due to a class not found exception in `occ check`. A separate execution of `occ check` looks like this:

```
occ check
An unhandled exception has been thrown:
Error: Class 'OCA\Files_Primary_S3\S3Storage' not found in /var/www/owncloud/lib/private/legacy/util.php:115
Stack trace:
```

The reason is that the apps are installed https://github.com/owncloud-ansible/owncloud/blob/75bb315f163b55d9ea94eb6aae76057cb16d55e1/tasks/main.yml#L28 after the config is written https://github.com/owncloud-ansible/owncloud/blob/75bb315f163b55d9ea94eb6aae76057cb16d55e1/tasks/setup.yml#L117 so the system doesn't know the class when `occ check` is executed in https://github.com/owncloud-ansible/owncloud/blob/75bb315f163b55d9ea94eb6aae76057cb16d55e1/tasks/setup.yml#L126
